config/routes.rb
Rails.application.routes.draw do
  namespace :api do
   resources :jobs, only: [:index, :create, :destroy, :update]
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
  # before_action :set_job, only: [:show, :edit, :update, :destroy]

  # Get all job when page start
  def index
    render json:Job.all
  end

   def create
      job = Job.create(job_params)
      render json: job
    end

    def destroy
      Job.destroy(params[:id])
    end

    def update
      job = Job.find(params[:id])
      job.update_attributes(job_params)
      render json: job
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # only require job params and only permit defined keys to pass to model
    def job_params
      params.require(:job).permit(:title, :joburl, :applieddate, :company, :stack, :status, :address, :latitude, :longitude)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # null session for the API-style controllers because we have no use for the session object.
    protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/home/index.html.erb
<%= react_component('Main', prerender: true) %>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :joburl %>
    <%= form.text_area :joburl %>
  </div>

  <div class="field">
    <%= form.label :applieddate %>
    <%= form.date_select :applieddate %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_area :company %>
  </div>

  <div class="field">
    <%= form.label :stack %>
    <%= form.text_area :stack %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_area :status %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<%= react_component 'Main' %>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Joburl</th>
      <th>Applieddate</th>
      <th>Company</th>
      <th>Stack</th>
      <th>Status</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.joburl %></td>
        <td><%= job.applieddate %></td>
        <td><%= job.company %></td>
        <td><%= job.stack %></td>
        <td><%= job.status %></td>
        <td><%= job.address %></td>
          <% if false %>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Joburl:</strong>
  <%= @job.joburl %>
</p>

<p>
  <strong>Applieddate:</strong>
  <%= @job.applieddate %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Stack:</strong>
  <%= @job.stack %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job.status %>
</p>

<p>
  <strong>Address:</strong>
  <%= @job.address %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>JobNotes</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_pack_tag 'bootstrap' %>
        <%= stylesheet_pack_tag 'react_table' %>
        <!-- Following will make the react components availabe to our layout -->
        <%= javascript_pack_tag 'application' %>
        <!-- google api key -->
    </head>

    <body>
        <%= yield %>
    </body>
</html>